Parameters:
  Code:
    Description: "Inline code"
    Type: String
    Default: ""

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: "CloudFormationS3EmptyBucketPolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - s3:DeleteObject
            - s3:DeleteObjectVersion
            - s3:ListBucket
            - s3:ListBucketVersions
            Resource: arn:aws:s3:::*

  S3EmptyBucketFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "S3EmptyBucket"
      Code:
        ZipFile: !Ref Code
      Handler: "index.handler"
      Runtime: "nodejs6.10"
      Timeout: 30
      Role: !GetAtt LambdaExecutionRole.Arn

Outputs:
  S3EmptyBucketFunction:
    Value: !GetAtt S3EmptyBucketFunction.Arn
    Export:
      Name: "S3EmptyBucketFunction"
